version: '3'
services:
  mysql: 
    image: mysql:5.7 
    environment: 
      - MYSQL_ROOT_PASSWORD=password 
      - LANG=C.UTF-8 
    ports: 
      - 3306:3306 
    volumes: 
      - ./tmp/docker/mysql:/var/lib/mysql 
      - ./.docker/mysql.cnf:/etc/mysql/mysql.conf.d/custom.cnf
  redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server --requirepass password
    volumes:
      - ./tmp/docker/redis:/data
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    # volumes:
    #     - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
    #     - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
    #     - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_VHOST: my_vhost
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
